import type { Metadata } from "next";
import { Azeret_Mono, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CTASection from "@/components/CTASection";
import Header from "@/components/Header";
import { PopupProvider } from "@/components/form/PopupProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const azeretMono = Azeret_Mono({
  variable: "--font-azeret-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NIHT - India's No.1 AI-Driven Digital Marketing Institute",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${azeretMono.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PopupProvider >
          <Header />
          {children}
          <CTASection />
        </PopupProvider>
      </body>
    </html>
  );
}
